# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.contrib.auth.models
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalDetails',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('days', models.CharField(unique=True, max_length=15)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('area_name', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('available', models.CharField(max_length=15, choices=[(b'AVAILABLE', b'AVAILABLE'), (b'NOT_AVAILABLE', b'NOT_AVAILABLE')])),
                ('start_date', models.DateField(default=None, null=True, blank=True)),
                ('end_date', models.DateField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillCycle',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bill_cycle_code', models.CharField(max_length=100)),
                ('bill_cycle_name', models.CharField(max_length=100, null=True)),
                ('created_by', models.CharField(max_length=500)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('area', models.ForeignKey(blank=True, to='adminapp.Area', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('city', models.CharField(default=None, max_length=500)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('employee_type', models.CharField(max_length=500)),
                ('created_by', models.CharField(max_length=500)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='RouteDetail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('route_code', models.CharField(max_length=500)),
                ('month', models.CharField(max_length=20)),
                ('bill_month', models.CharField(max_length=20, null=True)),
                ('created_by', models.CharField(max_length=50, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=50, null=True, blank=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_on', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('billcycle', models.ForeignKey(blank=True, to='adminapp.BillCycle', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RT_DETAILS',
            fields=[
                ('ID', models.AutoField(max_length=10, serialize=False, primary_key=True)),
                ('CIS_DIVISION', models.CharField(max_length=254, null=True, blank=True)),
                ('BILL_CYC_CD', models.CharField(max_length=254, null=True, blank=True)),
                ('BU', models.CharField(max_length=254, null=True, blank=True)),
                ('PC', models.CharField(max_length=254, null=True, blank=True)),
                ('CONS_NO', models.CharField(max_length=254, null=True, blank=True)),
                ('ACCOUNT_ID', models.CharField(max_length=254, null=True, blank=True)),
                ('MU_NO', models.CharField(max_length=254, null=True, blank=True)),
                ('CONS_NAME', models.CharField(max_length=254, null=True, blank=True)),
                ('FATH_HUS_NAME', models.CharField(max_length=254, null=True, blank=True)),
                ('ADD1', models.CharField(max_length=254, null=True, blank=True)),
                ('ADD2', models.CharField(max_length=254, null=True, blank=True)),
                ('ADD3', models.CharField(max_length=254, null=True, blank=True)),
                ('VILLAGE', models.CharField(max_length=254, null=True, blank=True)),
                ('PREV_MONTH', models.CharField(max_length=254, null=True, blank=True)),
                ('BILL_MONTH', models.CharField(max_length=254, null=True, blank=True)),
                ('CURR_MONTH', models.CharField(max_length=254, null=True, blank=True)),
                ('BILL_NO', models.CharField(max_length=254, null=True, blank=True)),
                ('TRF_CATG', models.CharField(max_length=254, null=True, blank=True)),
                ('CONN_DATE', models.CharField(max_length=254, null=True, blank=True)),
                ('CONS_STATUS', models.CharField(max_length=254, null=True, blank=True)),
                ('LOAD', models.CharField(max_length=20, null=True, blank=True)),
                ('LOAD_UNIT_CD', models.CharField(max_length=254, null=True, blank=True)),
                ('DUTY_CD', models.CharField(max_length=254, null=True, blank=True)),
                ('URBAN_FLG', models.CharField(max_length=254, null=True, blank=True)),
                ('FEEDER_CD', models.CharField(max_length=254, null=True, blank=True)),
                ('FEEDER_NAME', models.CharField(max_length=254, null=True, blank=True)),
                ('DTC_CD', models.CharField(max_length=254, null=True, blank=True)),
                ('DTC_DESC', models.CharField(max_length=500, null=True, blank=True)),
                ('AREA_CD', models.CharField(max_length=254, null=True, blank=True)),
                ('AREA_NAME', models.CharField(max_length=254, null=True, blank=True)),
                ('ROUTE', models.CharField(max_length=254, null=True, blank=True)),
                ('SEQUENCE', models.CharField(max_length=254, null=True, blank=True)),
                ('GR_NO', models.CharField(max_length=254, null=True, blank=True)),
                ('RD_NO', models.CharField(max_length=254, null=True, blank=True)),
                ('POLE_NO', models.CharField(max_length=254, null=True, blank=True)),
                ('METER_NO', models.CharField(max_length=254, null=True, blank=True)),
                ('MTR_INST_DT', models.DateField(null=True, blank=True)),
                ('MTR_REPL_DT', models.DateField(null=True, blank=True)),
                ('METER_PHASE', models.CharField(max_length=254, null=True, blank=True)),
                ('MAKE', models.CharField(max_length=254, null=True, blank=True)),
                ('METER_DIGIT', models.CharField(max_length=254, null=True, blank=True)),
                ('MTR_TYPE', models.CharField(max_length=254, null=True, blank=True)),
                ('MF', models.CharField(max_length=254, null=True, blank=True)),
                ('PREVIOUS_RTG_DT', models.DateField(null=True, blank=True)),
                ('CURRENT_RTG_DT', models.DateField(null=True, blank=True)),
                ('PREV_RTG', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('CURR_RTG', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('CURR_RTG_STTS', models.CharField(max_length=254, null=True, blank=True)),
                ('PREV_RTG_STTS', models.CharField(max_length=254, null=True, blank=True)),
                ('AVG', models.CharField(max_length=254, null=True, blank=True)),
                ('LCR_UNIT', models.CharField(max_length=254, null=True, blank=True)),
                ('LATTITUDE', models.CharField(max_length=254, null=True, blank=True)),
                ('LONITUDE', models.CharField(max_length=254, null=True, blank=True)),
            ],
            options={
                'db_table': 'RT_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='RT_MASTER',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CIS_DIVISION', models.CharField(max_length=20, null=True, blank=True)),
                ('BILL_MONTH', models.CharField(max_length=20, null=True, blank=True)),
                ('BILL_CYC_CD', models.CharField(max_length=20, null=True, blank=True)),
                ('ROUTE_ID', models.CharField(max_length=20, null=True, blank=True)),
                ('INSERTEDON', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'RT_MASTER',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('state', models.CharField(max_length=500, blank=True)),
                ('created_by', models.CharField(max_length=500, null=True, blank=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='UPLD_MTR_RDNG',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('BILL_CYC', models.CharField(max_length=254, null=True, blank=True)),
                ('BILL_MONTH', models.CharField(max_length=254, null=True, blank=True)),
                ('CUSTOMER_ID', models.CharField(max_length=254, null=True, blank=True)),
                ('DOCUMENT_TYPE', models.CharField(max_length=254, null=True, blank=True)),
                ('DTR_NO', models.IntegerField(null=True, blank=True)),
                ('ESTIMATED', models.CharField(max_length=254, null=True, blank=True)),
                ('FEEDER_CODE', models.CharField(max_length=254, null=True, blank=True)),
                ('IMAGE_PATH', models.CharField(max_length=254, null=True, blank=True)),
                ('INSERTEDON', models.DateTimeField(default=django.utils.timezone.now)),
                ('LATTITUDE', models.CharField(max_length=254, null=True, blank=True)),
                ('LONGITUDE', models.CharField(max_length=254, null=True, blank=True)),
                ('MDI', models.CharField(max_length=254, null=True, blank=True)),
                ('METER_READING', models.CharField(max_length=254, null=True, blank=True)),
                ('METER_STATUS', models.CharField(max_length=254, null=True, blank=True)),
                ('PC', models.CharField(max_length=254, null=True, blank=True)),
                ('PF', models.CharField(max_length=254, null=True, blank=True)),
                ('READER_ID', models.CharField(max_length=254, null=True, blank=True)),
                ('READING_DATE', models.CharField(max_length=254, null=True, blank=True)),
                ('ROUTE', models.CharField(max_length=254, null=True, blank=True)),
                ('SEQUENCE', models.CharField(max_length=254, null=True, blank=True)),
            ],
            options={
                'db_table': 'UPLD_MTR_RDNG',
            },
        ),
        migrations.CreateModel(
            name='UserPrivilege',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('privilege', models.CharField(max_length=500)),
                ('created_by', models.CharField(max_length=500)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('parent', models.ForeignKey(blank=True, to='adminapp.UserPrivilege', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_no', models.CharField(max_length=15)),
                ('address_line_1', models.CharField(max_length=500, blank=True)),
                ('address_line_2', models.CharField(max_length=500, blank=True)),
                ('pincode', models.CharField(max_length=500, blank=True)),
                ('employee_id', models.CharField(max_length=100, blank=True)),
                ('type', models.CharField(default=b'WEB_USER', max_length=20, choices=[(b'WEB_USER', b'WEB_USER'), (b'METER_READER', b'METER_READER'), (b'VALIDATOR_1', b'VALIDATOR_1'), (b'VALIDATOR_2', b'VALIDATOR_2'), (b'APPROVAL', b'APPROVAL')])),
                ('status', models.CharField(default=b'ACTIVE', max_length=20, choices=[(b'ACTIVE', b'ACTIVE'), (b'INACTIVE', b'INACTIVE')])),
                ('created_by', models.CharField(max_length=500)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('city', models.ForeignKey(to='adminapp.City', null=True)),
                ('employee_type', models.ForeignKey(blank=True, to='adminapp.EmployeeType', null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('role', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500, null=True, blank=True)),
                ('status', models.CharField(default=b'Active', max_length=20, choices=[(b'Active', b'Active'), (b'Inactive', b'Inactive')])),
                ('created_by', models.CharField(max_length=500)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
                ('privilege', models.ManyToManyField(to='adminapp.UserPrivilege')),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('utility', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=500)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('zone_name', models.CharField(max_length=250)),
                ('created_by', models.CharField(max_length=500, null=True)),
                ('updated_by', models.CharField(max_length=500, null=True, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(null=True, blank=True)),
                ('is_deleted', models.BooleanField(default=False, choices=[(True, True), (False, False)])),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, to='adminapp.UserRole', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.ForeignKey(to='adminapp.State', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, to='adminapp.State', null=True),
        ),
        migrations.AddField(
            model_name='billcycle',
            name='city',
            field=models.ForeignKey(blank=True, to='adminapp.City', null=True),
        ),
        migrations.AddField(
            model_name='billcycle',
            name='utility',
            field=models.ForeignKey(blank=True, to='adminapp.Utility', null=True),
        ),
        migrations.AddField(
            model_name='billcycle',
            name='zone',
            field=models.ForeignKey(blank=True, to='adminapp.Zone', null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='validator',
            field=models.ForeignKey(related_name='validator', to='adminapp.UserProfile', null=True),
        ),
        migrations.AddField(
            model_name='approvaldetails',
            name='approval',
            field=models.ForeignKey(related_name='approvals', to='adminapp.UserProfile', null=True),
        ),
    ]
